#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "apt"
cookbook "vim", {}
cookbook "git", {}
cookbook "mysql", {}
cookbook "nginx", {}
cookbook "php", {}
cookbook "composer", {}
cookbook "database", {}